version: '2.3'
volumes:
  dados:
services:
  db:
    image: mysql:5.6
    volumes:
      - type: bind
        source: ./src/main/resources/db/migration
        target: /docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=twitter
      - MYSQL_PASSWORD=twitter
      - MYSQL_DATABASE=twitter
    ports:
      - 3306:3306
  api-get-tweets:
    image: edivaldo100/api-get-tweets:1.0.0
    container_name: api-get-tweets
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=twitter
      - DATABASE_PASSWORD=twitter
      - DATABASE_NAME=twitter
      - DATABASE_PORT=3306
  api-minera-tweets:
    image: edivaldo100/api-minerar-twitter:1.0.0
    container_name: api-minerar-twitter
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=twitter
      - DATABASE_PASSWORD=twitter
      - DATABASE_NAME=twitter
      - DATABASE_PORT=3306