CREATE TABLE twitter.idioma (
  id bigint(10) NOT NULL AUTO_INCREMENT,
  codigo_idioma varchar(255) DEFAULT NULL,
  idioma varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en','Inglês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ar','Árabe');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('pt-br','Português do Brasil');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('bg','Búlgaro');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('cs','Checo');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('da','Dinamarquês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('nl','Holandês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-US','Inglês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('fi','Finlandês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('fr','Francês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('de','Alemão');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('el','Grego');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('he','Hebraico');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('hi','Híndi');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('hu','Húngaro');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('id','Indonésio');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('it','Italiano');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ja','Japonês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ko','Coreano');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('no','Norueguês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('pl','Polonês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ro','Romeno');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ru','Russo');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('zh-cn','Chinês simplificado');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('es','Espanhol');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('sv','Sueco');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('th','Tailandês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('zh-tw','Chinês tradicional');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('tr','Turco');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('vi','Vietnamita');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-gb','Inglês Britânico');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('fr-ca','Francês (Canadá)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('pt','Português');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('es-419','Espanhol (América Latina)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('es-es','Espanhol (Europa)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-ca','Inglês (Canadá)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('fil','Filipino');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ms','Malaio');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('sq','Albanês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ca','Catalão');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('hr','Croata');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('et','Estoniano');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('is','Islandês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ku','Curdo');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('lv','Letão');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('lt','Lituano');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('fa','Persa');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('sr','Sérvio');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('sk','Eslovaco');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('sl','Esloveno');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('uk','Ucraniano');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ur','Urdu');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ar-eg','Árabe (Egito)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-au','Inglês (Austrália)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('de-at','Alemão (Áustria)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-be','Inglês (Bélgica)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-150','Inglês (Europa)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-in','Inglês (Índia)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-ie','Inglês (Irlanda)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-nz','Inglês (Nova Zelândia)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-ph','Inglês (Filipinas)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-sg','Inglês (Cingapura)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-za','Inglês (África do Sul)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-001','Inglês (Global)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('nl-be','Flamengo');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('fr-be','Francês (Bélgica)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('fr-fr','Francês (França)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('es-mx','Espanhol (México)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('sr-me','Sérvio (Montenegro)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('fr-ch','Francês (Suíça)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('de-ch','Alemão (Suíça)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('zh-sg','Chinês (simplificado - Cingapura)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('zh-hk','Chinês (tradicional - Hong Kong, RAE da China)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('zh-mo','Chinês (tradicional - Macau, RAE da China)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-gu','Inglês (Guam)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-hk','Inglês (Hong Kong)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-il','Inglês (Israel)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-lr','Inglês (Libéria)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-my','Inglês (Malásia)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-se','Inglês (Suécia)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('en-ch','Inglês (Suíça)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('fr-002','Francês (DT)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('de-x-informal','Alemão (informal)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('de-lu','Alemão (Luxemburgo)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('it-ch','Italiano (Suíça)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('nn','Norueguês (Nynorsk)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('nb','Norueguês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ru-kz','Russo (Cazaquistão)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('es-ar','Espanhol (Argentina)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('es-cl','Espanhol (Chile)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('es-co','Espanhol (Colômbia)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('es-pe','Espanhol (Peru)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('es-us','Espanhol (Estados Unidos)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('es-ve','Espanhol (Venezuela)');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('af','Africâner');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('am','Amárico');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('hy','Armênio');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('az','Azerbaijano');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('bn','Bengali');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('eu','Basco');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('be','Bielorrusso');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('bs','Bósnio');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('my','Birmanês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('fo','Feroês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('gl','Galego');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ka','Georgiano');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('gu','Guzerate');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ga','Irlandês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('kn','Kannada');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('kk','Cazaque');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('km','Khmer');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ky','Quirguiz');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('mk','Macedônio');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ml','Malaiala');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('mt','Maltês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('mr','Marati');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('mn','Mongol');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ne','Nepalês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ps','Pachto');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('pa','Punjabi');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('si','Cingalês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('so','Somali');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('sw','Suaíli');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('tl','Filipino');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('tg','Tadjique');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('ta','Tâmil');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('te','Télugo');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('tk','Turcomeno');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('uz','Uzbeque');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('cy','Galês');
INSERT INTO twitter.idioma (codigo_idioma, idioma) VALUES('xh','Xhosa');
 
